### ISSUE TITLE
Update on Risk of Openness Index

### ISSUE THREAD

**Issue by RuijingZ** [OxCGRT/covid-policy-scratchpad#4]
Hello,

I noticed that risk of openness index file has not been updated for almost one week. May I know when will it resume updating again?

Best,
Ruijing

**Comment by saptahash** [comment]
Hi @RuijingZ, 

Thanks for raising this! We missed out on changing the automation schedule back to daily cron jobs after some testing over the past week. It's fixed now, and hopefully we should have an update tonight!

**Comment by RuijingZ** [comment]
Thank you!

**Comment by RuijingZ** [comment]
> Hi @RuijingZ,
> 
> Thanks for raising this! We missed out on changing the automation schedule back to daily cron jobs after some testing over the past week. It's fixed now, and hopefully we should have an update tonight!

Thank you!
